valid_email = "gimalov.98@mail.ru"
valid_password = "QW67$TAEL$_vQeJ"
phone = "89170766996"
random_email = "sdhjhdffggqws@mail.com"
random_password = "Correctpass66!"

"""Ссылки для тестирования страницы ростелекома"""

auth_url = "https://b2c.passport.rt.ru"
base_url = "https://msk.rt.ru/"
business_url = "https://msk.rt.ru/b2b"
operators_url = "https://msk.rt.ru/b2o"
blog_url = "https://blog.rt.ru/"
about_company_url = "https://www.company.rt.ru/about/info/"
for_partners_url = "https://msk.rt.ru/partners"
for_investors_url = "https://www.company.rt.ru/ir/"
games_url = "https://msk.rt.ru/play"
bonuses_url = "https://msk.rt.ru/bonus"
help_url = "https://msk.rt.ru/care"
payment_page_url = "https://msk.rt.ru/payment"
payment_other_organizations_url = "https://payment.rt.ru/rt/"
find_payment_url = "https://msk.rt.ru/payment_search"
error_not_found_text = "К сожалению, мы не смогли найти то, что вы искали"

"""Ссылки для тестирования страниц атворизации, регистрации, восстановления ростелекома"""

elk_url = "https://lk.rt.ru/"
onlime_url = "https://my.rt.ru/"
start_web_url = "https://start.rt.ru/"
smart_home_url = "https://lk.smarthome.rt.ru/"
key_web_url = "https://key.rt.ru/"
agreement_url = "https://b2c.passport.rt.ru/sso-static/agreement/agreement.html"
