"""Локаторы для тестирования главной страницы ростелеком"""

l_landing_btn = "a.rtk-logo__click-area"
l_for_me_btn = "//div/a/span[contains(text(), 'Для меня')]"
l_for_business = "//div/a/span[contains(text(), 'Для бизнеса')]"
l_for_operators = "//div/a/span[contains(text(), 'Для операторов')]"
l_for_blog_btn = "//div/a/span[contains(text(), 'Блог')]"
l_drop_btn = "div.rtk-links__drop div.rtk-links__drop-btn svg.rt-sys-icon"
l_about_company = "//div/a/span[contains(text(), 'О компании')]"
l_for_partners = "//div/a/span[contains(text(), 'Для партнёров')]"
l_for_investors = "//div/a/span[contains(text(), 'Для инвесторов')]"
l_games_btn = "//div/a/span[contains(text(), 'Игры')]"
l_bonuses_btn = "//div/a/span[contains(text(), 'Бонусы')]"
l_help_btn = "//div/a/span[contains(text(), 'Помощь')]"
l_payment_btn = "div.rtk-links__drop-btn div.rtk-links__drop-btn-lbl"
l_payment_rostelecom = "//div/a/span[contains(text(), 'Услуги Ростелекома')]"
l_other_organizations = "//div/a/span[contains(text(), 'Оплата других организаций')]"
l_find_payment = "//div/a/span[contains(text(), 'Поиск платежа')]"
l_other_org_body = "div.rt-col.sp-t-1 a"
l_find_payment_body = ("div.rt-col a.rt-arrow-block.sp-v-1-3.sp-l-1-3.sp-r-2-3.md-sp-h-1.rt-sys-icon-hover--orange."
                       "payment-search.height-fill")
l_banner_body = "div.rt-col div.checkup-banner__block.sp-v-orange"
l_personal_account_field = "//div/label/input[@name='account-input']"
l_amount_field = "//div/label/input[@name='sum-input']"
l_move_to_pay_btn = "//div/span/div/button[@qa-id='Button']"
